apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: arris-stats
  name: arris-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: arris-stats
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: arris-stats
    spec:
      containers:
        - env:
            - name: modem_model
              value: sb8200
            - name: influx_url
              value: http://10.96.105.199
          image: ghcr.io/sarabveer/arris_cable_modem_stats:latest
          name: arris-stats
      restartPolicy: Always
