services:
  arris_stats:
    image: augnix/cable_modem_stats
    container_name: arris_stats
    restart: unless-stopped
    network_mode: host
    environment:
      - modem_model=sb8200
      - arris_stats_debug=true
